// Code generated by MockGen. DO NOT EDIT.
// Source: home.go

// Package controller is a generated GoMock package.
package controller

import (
	app "layoutrender-boilerplate/app"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHomeApp is a mock of HomeApp interface.
type MockHomeApp struct {
	ctrl     *gomock.Controller
	recorder *MockHomeAppMockRecorder
}

// MockHomeAppMockRecorder is the mock recorder for MockHomeApp.
type MockHomeAppMockRecorder struct {
	mock *MockHomeApp
}

// NewMockHomeApp creates a new mock instance.
func NewMockHomeApp(ctrl *gomock.Controller) *MockHomeApp {
	mock := &MockHomeApp{ctrl: ctrl}
	mock.recorder = &MockHomeAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHomeApp) EXPECT() *MockHomeAppMockRecorder {
	return m.recorder
}

// HomeRender mocks base method.
func (m *MockHomeApp) HomeRender() app.LayoutRender {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HomeRender")
	ret0, _ := ret[0].(app.LayoutRender)
	return ret0
}

// HomeRender indicates an expected call of HomeRender.
func (mr *MockHomeAppMockRecorder) HomeRender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HomeRender", reflect.TypeOf((*MockHomeApp)(nil).HomeRender))
}
